# Generated by Django 4.1.4 on 2024-10-29 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0005_student_completed_student_subject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='student_name',
        ),
    ]
