# Generated by Django 4.1.4 on 2024-10-29 16:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subjects', '0007_alter_student_subject'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('name', 'subject')},
        ),
    ]
